### PR TITLE
shirt yes

### PR DESCRIPTION
**Pull request by ghost**
Finalized.

### CODE REVIEW

**Comment by jacobmischka** [comment]
does this actually count. I really hope not.

**Comment by sagebind** [comment]
:smile:

**Comment by sagebind** [comment]
It does technically, but if a human decides to review briefly the PRs first, this probably won't fly.

**Comment by ghost** [comment]
Hi Jacob! I'm actually a mildly competent programmer and since this is a promotional Github is having, I don't really feel like I need to take it that seriously. PRs are very useful when used correctly.

If you're experiencing anguish as a result of my shenanigans, may I kindly direct you to the report button? Only then will peace and justice will be restored. 

Many thank-yous for your benevolent contribution to the universe, Jacob!

**Comment by sagebind** [comment]
@jacobmischka regularly snoops around my abundant GitHub activity. Looks like you've joined the club then, @woodej01?

**Comment by ghost** [comment]
This is not allowed. He will be hearing from my attorneys.

**Comment by jacobmischka** [comment]
But you were the one breaking the rules! I'm just a narc and last I checked that's not illegal.

**Comment by ghost** [comment]
1) I'm not breaking any rules.

2) You don't sue someone for breaking the law; you sue someone for damages, being a nuisance, and/or violating a contract. 

Plus I was kidding. :p

**Pull request closed without merging**
